[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "robotframework-tablelibrary"
version = "0.0.1"
description = "A Robot Framework library providing generic table keywords for several table file type like csv or excel."
# authors = [
#     { name = "Author", email = "Email" }
# ]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "robotframework>=6.0",
]

[project.optional-dependencies]
dev = [
    "hatch",
    "pytest"
]

[project.urls]
Homepage = "https://github.com/MarvKler/robotframework-tablelibrary"
Repository = "https://github.com/MarvKler/robotframework-tablelibrary"

[tool.hatch.build.targets.wheel]
packages = ["robotframework-tablelibrary"]
