name: Execute Acceptance / Unit Tests

on:
  push:
    # branches:
    #   - main
    paths:
      - '**.py'
      - pyproject.toml
  pull_request:
    paths:
      - '**.py'
      - pyproject.toml

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Hatch
      run: pip install hatch

    - name: Install dependencies
      run: hatch env create dev

    - name: Build wheel with Hatch
      run: hatch build

    - name: Run robot framework acceptance-tests
      run: hatch run dev:atest

  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Hatch
      run: pip install hatch

    - name: Install dependencies
      run: hatch env create dev

    - name: Build wheel with Hatch
      run: hatch build

    - name: Run unit tests with pytest
      run: hatch run dev:utest
